name: 'Create Release or Hotfix Pull Request'
description: 'Create Release or Hotfix Pull Request'
inputs:
  current-branch:  # the name of new branch
    description: 'Name of new pushed branch'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash