project_package: src.applications.image_trimmer.processors
business_process: MLS Media Image Trimmer Lambda
business_process_id: P1010
business_activity: MLS Media Image Trimmer
business_activity_id: P1010-A060

kafka:
  config:
    bootstrap_servers: ${DIP_KAFKA_BOOTSTRAP_SERVERS}
  conformed_media_dlq_topic_name: ${CONFORMED_MEDIA_KAFKA_TOPIC_DLQ}

s3:
  media_conformed_files_s3_bucket_name: ${MEDIA_CONFORMED_FILES_S3_BUCKET_NAME}
  media_raw_files_s3_bucket_name: ${MEDIA_RAW_FILES_S3_BUCKET_NAME}

write_log_debug: ${WRITE_LOG_DEBUG}
extensions: ${EXTENSIONS}
pixel_threshold: ${PIXEL_THRESHOLD}
max_resize_width: ${MAX_RESIZE_WIDTH}
max_resize_height: ${MAX_RESIZE_HEIGHT}
white_threshold: ${WHITE_THRESHOLD}
cropping_offset_value: ${CROPPING_OFFSET_VALUE}
image_save_quality_value: ${MAX_SAVE_QUALITY_VALUE}