name: CI - tags/*.*.*
# Controls when the action will run.
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  # This workflow contains a single job called "build"
  build:
    # if: ${{ startsWith(github.ref, 'refs/tags/*.*.*') }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "RELEASE_VERSION='0.0.3'" >> $GITHUB_ENV

      - name: Check Tag
        id: check-tag
        shell: bash
        run: |
          if [[ ${{ env.RELEASE_VERSION }} =~ ^([0-9]+\.){0,2}(\*|[0-9]+)$ ]]; then
                    echo ::set-output name=match::true
          fi

      - name: Metch result
        if: steps.check-tag.outputs.match == 'true'
        run: echo Hello from jenn