name: Create Release or Hotfix Pull Request
on:
  push:
    branches:
      - release/*
      - hotfix/*

jobs:
  creater-elease-or-hotfix-pr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        dev-branch:
          - develop
        prod-branch:
          - main

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set env Branch
      if: success()
      run: echo "CURRENT_BRANCH=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

#    - name: Extract version from release branch name
#      if: ${{ startsWith(env.CURRENT_BRANCH, 'release/') }}
#      run: |
#        echo "BRANCH_PRE=release" >> $GITHUB_ENV
#
#    - name: Extract version from hotfix branch name
#      if: ${{ startsWith(env.CURRENT_BRANCH, 'hotfix/') }}
#      run: |
#        echo "BRANCH_PRE=hotfix" >> $GITHUB_ENV

#    - name: New release version
#      if: success()
#      run: |
#        VERSION=${CURRENT_BRANCH#${{env.BRANCH_PRE}}/}
#        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create pull request into master
      if: success()
      uses: vsoch/pull-request-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: ${{ matrix.prod-branch }}
        PULL_REQUEST_FROM_BRANCH: ${{ env.CURRENT_BRANCH }}
        PULL_REQUEST_TITLE: ${{ env.CURRENT_BRANCH }} into ${{ matrix.prod-branch }}
        PULL_REQUEST_TEAM_REVIEWERS: ${{ github.event.issue.user.login }}
        PULL_REQUEST_DRAFT: true
        PULL_REQUEST_BODY: |
          Hi!
          This PR was created by Github workflow.

    - name: Create pull request to develop
      if: success()
      uses: vsoch/pull-request-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: ${{ matrix.dev-branch }}
        PULL_REQUEST_FROM_BRANCH: ${{ env.CURRENT_BRANCH }}
        PULL_REQUEST_TITLE: ${{ env.CURRENT_BRANCH }} into ${{ matrix.dev-branch }}
        PULL_REQUEST_TEAM_REVIEWERS: ${{ github.event.issue.user.login }}
        PULL_REQUEST_DRAFT: true
        PULL_REQUEST_BODY: |
          Hi!
          This PR was created by Github workflow.