name: Make a new release or hotfix branch workflow
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Semantic version -M (majo) -m (minor) -p (patch) -h (hotfix patch)
        required: true
        default: '-p'

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Make a new release
        shell: bash
        run: |
          chmod +x ./scripts/make-release.sh
          ./scripts/make-release.sh "${{ github.event.inputs.release-version }}" "${{ github.actor }}"
