name: Manual-Make-Release-2
on:
  push:
    branches:
      - release/*
      - hotfix/*
  workflow_dispatch:
    inputs:
      release-version:
        description: Semantic version -M (majo) -m (minor) -p (patch) -h (hotfix patch)
        required: true
        default: '-p'

jobs:
  make-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        dev-branch:
          - develop
        prod-branch:
          - main

    steps:
      - uses: actions/checkout@v2

      - name: job
        run: echo ${{ github.job }}
      - name: ref
        run: echo ${{ github.ref }}
      - name: sha
        run: echo ${{ github.sha }}
      - name: repository
        run: echo ${{ github.repository }}
      - name: repository_owner
        run: echo ${{ github.repository_owner }}
      - name: actor
        run: echo ${{ github.actor }}
      - name: run_id
        run: echo ${{ github.run_id }}
      - name: workflow
        run: echo ${{ github.workflow }}
      - name: event_name
        run: echo ${{ github.event_name }}
      - name: event.ref
        run: echo ${{ github.event.ref }}
      - name: action
        run: echo ${{ github.action }}

      - name: Get new release branch name
        if: ${{ (contains(github.event_name, 'workflow_dispatch')) || false }}
        shell: bash
        run: |
          chmod +x ./.github/scripts/new-release-version.sh
          echo "::set-output name=NEW_BRANCH_NAME::$(./.github/scripts/new-release-version.sh ${{ github.event.inputs.release-version }})"
        id: new-branch-name

      - name: create branch
        if: ${{ (contains(github.event_name, 'workflow_dispatch')) || false }}
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.new-branch-name.outputs.NEW_BRANCH_NAME  }}

      - name: Create pull request into master
        if: ${{ (contains(github.event_name, 'workflow_dispatch'))  && github.ref == 'refs/heads/develop' || (contains(github.event_name, 'push')) && (contains(github.ref, 'refs/heads/hotfix')) || false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "${{ steps.new-branch-name.outputs.NEW_BRANCH_NAME }} into ${{ matrix.prod-branch }}" --base ${{ matrix.prod-branch }} -H ${{ steps.new-branch-name.outputs.NEW_BRANCH_NAME }} -r "${{ github.actor }}" -d -b "Hi!\nThis PR was created by Github workflow."

#      - name: Condition to PR to develop push
#        if: ${{ (contains(github.event_name, 'push')) && (contains(github.ref, 'refs/heads/release/')) }}
#        run: |
#          echo "PR to develop"

      - name: Create pull request to develop
        if: ${{ (contains(github.event_name, 'workflow_dispatch'))  && github.ref == 'refs/heads/main' || (contains(github.event_name, 'push')) && (contains(github.ref, 'refs/heads/release/')) || false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "${{ steps.new-branch-name.outputs.NEW_BRANCH_NAME }} into ${{ matrix.dev-branch }}" --base ${{ matrix.dev-branch }} -H ${{ steps.new-branch-name.outputs.NEW_BRANCH_NAME }} -r "${{ github.actor }}" -d -b "Hi!\nThis PR was created by Github workflow."
