name: Manual-Make-Release-2
# try
on:
  push:
    branches:
      - release/*
      - hotfix/*
  workflow_dispatch:
    inputs:
      release-version:
        description: Semantic version -M (majo) -m (minor) -p (patch) -h (hotfix patch)
        required: true
        default: '-p'

jobs:
  make-release-hotfix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        dev-branch:
          - develop
        prod-branch:
          - main

    steps:
      - uses: actions/checkout@v2

      - name: get-ref
        run: |
          echo ${{ github.ref }}

      - name: Get new release branch name
        if: ${{ (contains(github.event_name, 'workflow_dispatch')) || false }}
        shell: bash
        run: |
          chmod +x ./.github/scripts/new-release-version.sh
          echo "NEW_BRANCH_NAME=$(./.github/scripts/new-release-version.sh ${{ github.event.inputs.release-version }})" >> $GITHUB_ENV
#          echo "::set-output name=NEW_BRANCH_NAME::$(./.github/scripts/new-release-version.sh ${{ github.event.inputs.release-version }})" >> $GITHUB_ENV
#          NEW_BRANCH_NAME="$(./.github/scripts/new-release-version.sh ${{ github.event.inputs.release-version }})"
#           echo "$NEW_BRANCH_NAME" >> $GITHUB_ENV
        id: new-branch-name

      - name: create branch
        if: ${{ (contains(github.event_name, 'workflow_dispatch')) || false }}
        run: |
          git config user.name ${{ github.actor }}
          git config user.email noreply@github.com
          git checkout -b ${{ env.NEW_BRANCH_NAME }}
          git commit -a -m "new ${{ env.NEW_BRANCH_NAME  }} branch created."
          git push --set-upstream origin ${{ env.NEW_BRANCH_NAME }}
#   steps.new-branch-name.outputs.NEW_BRANCH_NAME
      - name: Get current Branch
        if: ${{ (contains(github.event_name, 'push')) }}
        run: |
          echo "NEW_BRANCH_NAME=${{github.ref_name}}" >> $GITHUB_ENV
#          echo "::set-output name=NEW_BRANCH_NAME::${{github.ref_name}}"
        id: current-branch-name

      - name: Set new branch name
        id: set-new-branch-name
        run:
          echo "::set-output name=NEW_BRANCH_NAME::${{ env.NEW_BRANCH_NAME }}"
    outputs:
      NEW_BRANCH_NAME: ${{ steps.set-new-branch-name.output.NEW_BRANCH_NAME }}

  create-pull-request:
    needs: [ make-release-hotfix ]
    uses: jennxu118/auto-deploy/.github/workflows/pull-request.yml@develop
    with:
      event_name: ${{ github.event_name }}
      ref: ${{ github.ref }}
      new_branch_name: ${{ needs.make-release-hotfix.outputs.NEW_BRANCH_NAME }}
      dev_branch_name: ${{ matrix.dev-branch }}
      prod_branch_name: ${{ matrix.prod-branch }}
      user_name: ${{ github.actor }}

#    secrets:
#      GITHUB_TOKEN: ${{ secretes.GITHUB_TOKEN }}


  # only trigger by manual create release branch and new commit to release branch
#  deploy-dev:
#    if:  ${{ !(contains(github.ref, 'refs/heads/hotfix')) || false }}
#    needs: [ make-release-hotfix ]
#    uses: jennxu118/auto-deploy/.github/workflows/deploy.yml@develop
#    with:
#      environment: Dev
#      user_name: $github.actor