on:
  workflow_call:
    inputs:
      event_name:
        description: github event name
        required: false
        type: string
      ref:
        description: github ref
        required: false
        type: string
      new_branch_name:
        description: the name of new branch
        required: false
        type: string
      dev_branch_name:
        description: the name of develop branch
        required: false
        type: string
      prod_branch_name:
        description: the name of prod branch
        required: false
        type: string
      pull_request_draft:
        description: should this be a draft PR?
        required: false
        type: string
        default: true
      pull_request_body:
        description: the body for the pull request
        required: false
        type: string
        default: |
          Hi!
          This PR was created by Github workflow.
      user_name:
        description: user name
        required: false
        type: string
#    secrets:
#       github_token:
#        required: true


jobs:
  call-job:
    runs-on: ubuntu-20.04
    steps:
      - name: echo
        run: |
          echo "event_name: ${{ inputs.event_name }}"
          echo "refs: ${{ inputs.refs }}"
          echo "prod_branch_name: ${{ inputs.prod_branch_name }}"
          echo "new_branch_name: ${{ inputs.new_branch_name }}"
          echo "user_name: ${{ inputs.user_name }}"

      - name: Create pull request into master
        if: ${{ (contains(inputs.event_name, 'workflow_dispatch'))  && inputs.ref == 'refs/heads/develop' || false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: vsoch/pull-request-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pull_request_branch: ${{ inputs.prod_branch_name }}
          pull_request_from_branch: ${{ inputs.new_branch_name }}
          pull_request_title: ${{ inputs.new_branch_name }} into ${{ inputs.prod_branch_name }}
          pull_request_team_reviewers: ${{ inputs.user_name }}

      - name: Create pull request to develop
        if: ${{ (contains(inputs.event_name, 'workflow_dispatch'))  && inputs.ref == 'refs/heads/main' || false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: vsoch/pull-request-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pull_request_branch: ${{ inputs.prod_branch_name }}
          pull_request_from_branch: ${{ inputs.new_branch_name }}
          pull_request_title: ${{ inputs.new_branch_name }} into ${{ inputs.dev_branch_name }}
          pull_request_team_reviewers: ${{ inputs.user_name }}

      - name: Create pull request into master by push
        if: ${{ (contains(inputs.event_name, 'push')) && (contains(inputs.ref, 'refs/heads/hotfix')) || false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: vsoch/pull-request-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pull_request_branch: ${{ inputs.prod_branch_name }}
          pull_request_from_branch: ${{ inputs.new_branch_name }}
          pull_request_title: ${{ inputs.new_branch_name }} into ${{ inputs.prod_branch_name }}
          pull_request_team_reviewers: ${{ inputs.user_name }}

      - name: Create pull request to develop by push
        if: ${{ (contains(inputs.event_name, 'push')) && (contains(inputs.ref, 'refs/heads/release')) || false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: vsoch/pull-request-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pull_request_branch: ${{ inputs.prod_branch_name }}
          pull_request_from_branch: ${{ inputs.new_branch_name }}
          pull_request_title: ${{ inputs.new_branch_name }} into ${{ inputs.dev_branch_name }}
          pull_request_team_reviewers: ${{ inputs.user_name }}
